version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: odontofast_backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
