version: '3' 
services:
  backend:
    build:
      context: ./docker  
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"
    container_name: odontofast_backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
